project_id: "slavayssiere-sandbox-462015"
base_domain: "zenika.slavayssiere.fr"
parent_zone_name: "slavayssiere-zenika"
cloudrun_min_instances: 0
cloudrun_max_instances: 2
alloydb_cpu: 2 # Coeurs virtuels (2 est le minimum pour AlloyDB en custom type)
waf_rate_limit: 100

image_users: "europe-west1-docker.pkg.dev/slavayssiere-sandbox-462015/z-gcp-summit-services/users_api:latest"
image_items: "europe-west1-docker.pkg.dev/slavayssiere-sandbox-462015/z-gcp-summit-services/items_api:latest"
image_competencies: "europe-west1-docker.pkg.dev/slavayssiere-sandbox-462015/z-gcp-summit-services/competencies_api:latest"
image_cv: "europe-west1-docker.pkg.dev/slavayssiere-sandbox-462015/z-gcp-summit-services/cv_api:latest"
image_prompts: "europe-west1-docker.pkg.dev/slavayssiere-sandbox-462015/z-gcp-summit-services/prompts_api:latest"
image_agent: "europe-west1-docker.pkg.dev/slavayssiere-sandbox-462015/z-gcp-summit-services/agent_api:latest"
admin_user: "sebastien.lavayssiere@zenika.com"
